# Generated by Django 4.2.4 on 2024-09-23 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lg", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="add_product",
        ),
    ]
